### ISSUE TITLE
Curdleproofs verification may not actually verify results

### ISSUE THREAD

**Issue by dapplion** [nalinbhardwaj/curdleproofs.pie#16]
Verify functions have the signature

https://github.com/nalinbhardwaj/curdleproofs.pie/blob/087fa9b6b597ee3342d43cfde2ab5ea871dec644/curdleproofs/curdleproofs/same_perm.py#L106

However in CurdleProofsProof.verify those return values are ignored, effectively ignoring the invalidity of the proofs

https://github.com/nalinbhardwaj/curdleproofs.pie/blob/087fa9b6b597ee3342d43cfde2ab5ea871dec644/curdleproofs/curdleproofs/curdleproofs.py#L212

https://github.com/nalinbhardwaj/curdleproofs.pie/blob/087fa9b6b597ee3342d43cfde2ab5ea871dec644/curdleproofs/curdleproofs/curdleproofs.py#L226

https://github.com/nalinbhardwaj/curdleproofs.pie/blob/087fa9b6b597ee3342d43cfde2ab5ea871dec644/curdleproofs/curdleproofs/curdleproofs.py#L257

**Comment by asn-d6** [comment]
Could that be because these proofs will assert if they are not valid?

**Comment by dapplion** [comment]
> Could that be because these proofs will assert if they are not valid?

## same_perm_proof

https://github.com/nalinbhardwaj/curdleproofs.pie/blob/087fa9b6b597ee3342d43cfde2ab5ea871dec644/curdleproofs/curdleproofs/same_perm.py#L128

https://github.com/nalinbhardwaj/curdleproofs.pie/blob/087fa9b6b597ee3342d43cfde2ab5ea871dec644/curdleproofs/curdleproofs/same_perm.py#L141-L144

Where grand_prod_proof

https://github.com/nalinbhardwaj/curdleproofs.pie/blob/087fa9b6b597ee3342d43cfde2ab5ea871dec644/curdleproofs/curdleproofs/grand_prod.py#L195

https://github.com/nalinbhardwaj/curdleproofs.pie/blob/087fa9b6b597ee3342d43cfde2ab5ea871dec644/curdleproofs/curdleproofs/grand_prod.py#L206-L207

and IPA proof returns bool for a preparation step

https://github.com/nalinbhardwaj/curdleproofs.pie/blob/087fa9b6b597ee3342d43cfde2ab5ea871dec644/curdleproofs/curdleproofs/ipa.py#L228-L232

and does not call verify on the msm accumulator

https://github.com/nalinbhardwaj/curdleproofs.pie/blob/087fa9b6b597ee3342d43cfde2ab5ea871dec644/curdleproofs/curdleproofs/ipa.py#L260-L262


## same_scalar_proof

Returns bool for an equality check

https://github.com/nalinbhardwaj/curdleproofs.pie/blob/087fa9b6b597ee3342d43cfde2ab5ea871dec644/curdleproofs/curdleproofs/same_scalar.py#L126-L129

## same_msm_proof

Returns bool for a preparation step 

https://github.com/nalinbhardwaj/curdleproofs.pie/blob/087fa9b6b597ee3342d43cfde2ab5ea871dec644/curdleproofs/curdleproofs/same_msm.py#L218-L221

and does not call verify on the msm accumulator

https://github.com/nalinbhardwaj/curdleproofs.pie/blob/087fa9b6b597ee3342d43cfde2ab5ea871dec644/curdleproofs/curdleproofs/same_msm.py#L247C25-L249

**Comment by asn-d6** [comment]
Yeah.... That seems like it needs fixing.
